@startuml

entity Categories {
* id INT <<PK>>
* category_name VARCHAR(255)
* parent_id INT NULL <<FK>>
--
* icon_url VARCHAR(255)
* is_active BOOLEAN
* is_recommended BOOLEAN
}

entity CategoriesTranslations {
* id INT <<PK>>
* name VARCHAR(255) NOT NUL
--
* category_id INT NOT NULL <<FK>>
* language_code VARCHAR(10) NOT NULL
* description TEXT
}

Categories ||--o{ CategoriesTranslations

@enduml